=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Discover unconfigured node details.
  class ClustermgmtV40ConfigNodeDiscoveryParams < ApiModelBase
    attr_accessor :address_type

    # IP addresses of the unconfigured nodes.
    attr_accessor :ip_filter_list

    # Unconfigured node UUIDs.
    attr_accessor :uuid_filter_list

    # Timeout for the workflow in seconds.
    attr_accessor :timeout

    # Interface name that is used for packet broadcasting.
    attr_accessor :interface_filter_list

    # Indicates if the discovery is manual or not.
    attr_accessor :is_manual_discovery

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'address_type' => :'addressType',
        :'ip_filter_list' => :'ipFilterList',
        :'uuid_filter_list' => :'uuidFilterList',
        :'timeout' => :'timeout',
        :'interface_filter_list' => :'interfaceFilterList',
        :'is_manual_discovery' => :'isManualDiscovery'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'address_type' => :'ClustermgmtV40ConfigAddressType',
        :'ip_filter_list' => :'Array<CommonV10ConfigIPAddress>',
        :'uuid_filter_list' => :'Array<String>',
        :'timeout' => :'Integer',
        :'interface_filter_list' => :'Array<String>',
        :'is_manual_discovery' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigNodeDiscoveryParams` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigNodeDiscoveryParams`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'address_type')
        self.address_type = attributes[:'address_type']
      end

      if attributes.key?(:'ip_filter_list')
        if (value = attributes[:'ip_filter_list']).is_a?(Array)
          self.ip_filter_list = value
        end
      end

      if attributes.key?(:'uuid_filter_list')
        if (value = attributes[:'uuid_filter_list']).is_a?(Array)
          self.uuid_filter_list = value
        end
      end

      if attributes.key?(:'timeout')
        self.timeout = attributes[:'timeout']
      end

      if attributes.key?(:'interface_filter_list')
        if (value = attributes[:'interface_filter_list']).is_a?(Array)
          self.interface_filter_list = value
        end
      end

      if attributes.key?(:'is_manual_discovery')
        self.is_manual_discovery = attributes[:'is_manual_discovery']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@ip_filter_list.nil? && @ip_filter_list.length > 1024
        invalid_properties.push('invalid value for "ip_filter_list", number of items must be less than or equal to 1024.')
      end

      if !@ip_filter_list.nil? && @ip_filter_list.length < 0
        invalid_properties.push('invalid value for "ip_filter_list", number of items must be greater than or equal to 0.')
      end

      if !@uuid_filter_list.nil? && @uuid_filter_list.length > 1024
        invalid_properties.push('invalid value for "uuid_filter_list", number of items must be less than or equal to 1024.')
      end

      if !@uuid_filter_list.nil? && @uuid_filter_list.length < 0
        invalid_properties.push('invalid value for "uuid_filter_list", number of items must be greater than or equal to 0.')
      end

      if !@interface_filter_list.nil? && @interface_filter_list.length > 1024
        invalid_properties.push('invalid value for "interface_filter_list", number of items must be less than or equal to 1024.')
      end

      if !@interface_filter_list.nil? && @interface_filter_list.length < 0
        invalid_properties.push('invalid value for "interface_filter_list", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@ip_filter_list.nil? && @ip_filter_list.length > 1024
      return false if !@ip_filter_list.nil? && @ip_filter_list.length < 0
      return false if !@uuid_filter_list.nil? && @uuid_filter_list.length > 1024
      return false if !@uuid_filter_list.nil? && @uuid_filter_list.length < 0
      return false if !@interface_filter_list.nil? && @interface_filter_list.length > 1024
      return false if !@interface_filter_list.nil? && @interface_filter_list.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ip_filter_list Value to be assigned
    def ip_filter_list=(ip_filter_list)
      if ip_filter_list.nil?
        fail ArgumentError, 'ip_filter_list cannot be nil'
      end

      if ip_filter_list.length > 1024
        fail ArgumentError, 'invalid value for "ip_filter_list", number of items must be less than or equal to 1024.'
      end

      if ip_filter_list.length < 0
        fail ArgumentError, 'invalid value for "ip_filter_list", number of items must be greater than or equal to 0.'
      end

      @ip_filter_list = ip_filter_list
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid_filter_list Value to be assigned
    def uuid_filter_list=(uuid_filter_list)
      if uuid_filter_list.nil?
        fail ArgumentError, 'uuid_filter_list cannot be nil'
      end

      if uuid_filter_list.length > 1024
        fail ArgumentError, 'invalid value for "uuid_filter_list", number of items must be less than or equal to 1024.'
      end

      if uuid_filter_list.length < 0
        fail ArgumentError, 'invalid value for "uuid_filter_list", number of items must be greater than or equal to 0.'
      end

      @uuid_filter_list = uuid_filter_list
    end

    # Custom attribute writer method with validation
    # @param [Object] interface_filter_list Value to be assigned
    def interface_filter_list=(interface_filter_list)
      if interface_filter_list.nil?
        fail ArgumentError, 'interface_filter_list cannot be nil'
      end

      if interface_filter_list.length > 1024
        fail ArgumentError, 'invalid value for "interface_filter_list", number of items must be less than or equal to 1024.'
      end

      if interface_filter_list.length < 0
        fail ArgumentError, 'invalid value for "interface_filter_list", number of items must be greater than or equal to 0.'
      end

      @interface_filter_list = interface_filter_list
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          address_type == o.address_type &&
          ip_filter_list == o.ip_filter_list &&
          uuid_filter_list == o.uuid_filter_list &&
          timeout == o.timeout &&
          interface_filter_list == o.interface_filter_list &&
          is_manual_discovery == o.is_manual_discovery
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [address_type, ip_filter_list, uuid_filter_list, timeout, interface_filter_list, is_manual_discovery].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
