=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigConfigType
    NTP_SERVER_CONFIG = "NTP_SERVER_CONFIG".freeze
    NAME_SERVER_CONFIG = "NAME_SERVER_CONFIG".freeze
    SMTP_SERVER_CONFIG = "SMTP_SERVER_CONFIG".freeze
    NFS_SUBNET_WHITELIST_CONFIG = "NFS_SUBNET_WHITELIST_CONFIG".freeze
    SNMP_SERVER_CONFIG = "SNMP_SERVER_CONFIG".freeze
    RSYSLOG_SERVER_CONFIG = "RSYSLOG_SERVER_CONFIG".freeze
    PULSE_CONFIG = "PULSE_CONFIG".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [NTP_SERVER_CONFIG, NAME_SERVER_CONFIG, SMTP_SERVER_CONFIG, NFS_SUBNET_WHITELIST_CONFIG, SNMP_SERVER_CONFIG, RSYSLOG_SERVER_CONFIG, PULSE_CONFIG, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigConfigType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigConfigType"
    end
  end
end
