=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigClusterFaultToleranceRef
    CFT_0_N_AND_0_D = "CFT_0N_AND_0D".freeze
    CFT_1_N_OR_1_D = "CFT_1N_OR_1D".freeze
    CFT_2_N_OR_2_D = "CFT_2N_OR_2D".freeze
    CFT_1_N_AND_1_D = "CFT_1N_AND_1D".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [CFT_0_N_AND_0_D, CFT_1_N_OR_1_D, CFT_2_N_OR_2_D, CFT_1_N_AND_1_D, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigClusterFaultToleranceRef.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigClusterFaultToleranceRef"
    end
  end
end
