=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigHttpProxyWhiteListTargetType
    IPV4_ADDRESS = "IPV4_ADDRESS".freeze
    IPV6_ADDRESS = "IPV6_ADDRESS".freeze
    IPV4_NETWORK_MASK = "IPV4_NETWORK_MASK".freeze
    DOMAIN_NAME_SUFFIX = "DOMAIN_NAME_SUFFIX".freeze
    HOST_NAME = "HOST_NAME".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [IPV4_ADDRESS, IPV6_ADDRESS, IPV4_NETWORK_MASK, DOMAIN_NAME_SUFFIX, HOST_NAME, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigHttpProxyWhiteListTargetType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigHttpProxyWhiteListTargetType"
    end
  end
end
