=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Host entity with its attributes.
  class ClustermgmtV40ConfigControllerVmReference < ApiModelBase
    attr_accessor :external_address

    attr_accessor :backplane_address

    # RDMA backplane address.
    attr_accessor :rdma_backplane_address

    attr_accessor :nat_ip

    # NAT port.
    attr_accessor :nat_port

    # Maintenance mode status.
    attr_accessor :is_in_maintenance_mode

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'external_address' => :'externalAddress',
        :'backplane_address' => :'backplaneAddress',
        :'rdma_backplane_address' => :'rdmaBackplaneAddress',
        :'nat_ip' => :'natIp',
        :'nat_port' => :'natPort',
        :'is_in_maintenance_mode' => :'isInMaintenanceMode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'external_address' => :'CommonV10ConfigIPAddress',
        :'backplane_address' => :'CommonV10ConfigIPAddress',
        :'rdma_backplane_address' => :'Array<CommonV10ConfigIPAddress>',
        :'nat_ip' => :'CommonV10ConfigIPAddress',
        :'nat_port' => :'Integer',
        :'is_in_maintenance_mode' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigControllerVmReference` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigControllerVmReference`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'external_address')
        self.external_address = attributes[:'external_address']
      end

      if attributes.key?(:'backplane_address')
        self.backplane_address = attributes[:'backplane_address']
      end

      if attributes.key?(:'rdma_backplane_address')
        if (value = attributes[:'rdma_backplane_address']).is_a?(Array)
          self.rdma_backplane_address = value
        end
      end

      if attributes.key?(:'nat_ip')
        self.nat_ip = attributes[:'nat_ip']
      end

      if attributes.key?(:'nat_port')
        self.nat_port = attributes[:'nat_port']
      end

      if attributes.key?(:'is_in_maintenance_mode')
        self.is_in_maintenance_mode = attributes[:'is_in_maintenance_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@rdma_backplane_address.nil? && @rdma_backplane_address.length > 1024
        invalid_properties.push('invalid value for "rdma_backplane_address", number of items must be less than or equal to 1024.')
      end

      if !@rdma_backplane_address.nil? && @rdma_backplane_address.length < 0
        invalid_properties.push('invalid value for "rdma_backplane_address", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@rdma_backplane_address.nil? && @rdma_backplane_address.length > 1024
      return false if !@rdma_backplane_address.nil? && @rdma_backplane_address.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rdma_backplane_address Value to be assigned
    def rdma_backplane_address=(rdma_backplane_address)
      if rdma_backplane_address.nil?
        fail ArgumentError, 'rdma_backplane_address cannot be nil'
      end

      if rdma_backplane_address.length > 1024
        fail ArgumentError, 'invalid value for "rdma_backplane_address", number of items must be less than or equal to 1024.'
      end

      if rdma_backplane_address.length < 0
        fail ArgumentError, 'invalid value for "rdma_backplane_address", number of items must be greater than or equal to 0.'
      end

      @rdma_backplane_address = rdma_backplane_address
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          external_address == o.external_address &&
          backplane_address == o.backplane_address &&
          rdma_backplane_address == o.rdma_backplane_address &&
          nat_ip == o.nat_ip &&
          nat_port == o.nat_port &&
          is_in_maintenance_mode == o.is_in_maintenance_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [external_address, backplane_address, rdma_backplane_address, nat_ip, nat_port, is_in_maintenance_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
