=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigClusterFunctionRef
    AOS = "AOS".freeze
    PRISM_CENTRAL = "PRISM_CENTRAL".freeze
    CLOUD_DATA_GATEWAY = "CLOUD_DATA_GATEWAY".freeze
    AFS = "AFS".freeze
    ONE_NODE = "ONE_NODE".freeze
    TWO_NODE = "TWO_NODE".freeze
    ANALYTICS_PLATFORM = "ANALYTICS_PLATFORM".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [AOS, PRISM_CENTRAL, CLOUD_DATA_GATEWAY, AFS, ONE_NODE, TWO_NODE, ANALYTICS_PLATFORM, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigClusterFunctionRef.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigClusterFunctionRef"
    end
  end
end
