=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigHypervisorState
    ACROPOLIS_NORMAL = "ACROPOLIS_NORMAL".freeze
    ENTERING_MAINTENANCE_MODE = "ENTERING_MAINTENANCE_MODE".freeze
    ENTERED_MAINTENANCE_MODE = "ENTERED_MAINTENANCE_MODE".freeze
    RESERVED_FOR_HA_FAILOVER = "RESERVED_FOR_HA_FAILOVER".freeze
    ENTERING_MAINTENANCE_MODE_FROM_HA_FAILOVER = "ENTERING_MAINTENANCE_MODE_FROM_HA_FAILOVER".freeze
    RESERVING_FOR_HA_FAILOVER = "RESERVING_FOR_HA_FAILOVER".freeze
    HA_FAILOVER_SOURCE = "HA_FAILOVER_SOURCE".freeze
    HA_FAILOVER_TARGET = "HA_FAILOVER_TARGET".freeze
    HA_HEALING_SOURCE = "HA_HEALING_SOURCE".freeze
    HA_HEALING_TARGET = "HA_HEALING_TARGET".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [ACROPOLIS_NORMAL, ENTERING_MAINTENANCE_MODE, ENTERED_MAINTENANCE_MODE, RESERVED_FOR_HA_FAILOVER, ENTERING_MAINTENANCE_MODE_FROM_HA_FAILOVER, RESERVING_FOR_HA_FAILOVER, HA_FAILOVER_SOURCE, HA_FAILOVER_TARGET, HA_HEALING_SOURCE, HA_HEALING_TARGET, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigHypervisorState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigHypervisorState"
    end
  end
end
