=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigSnmpProtocol
    UDP = "UDP".freeze
    UDP6 = "UDP6".freeze
    TCP = "TCP".freeze
    TCP6 = "TCP6".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [UDP, UDP6, TCP, TCP6, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigSnmpProtocol.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigSnmpProtocol"
    end
  end
end
