=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigUpgradeStatus
    PENDING = "PENDING".freeze
    DOWNLOADING = "DOWNLOADING".freeze
    QUEUED = "QUEUED".freeze
    PREUPGRADE = "PREUPGRADE".freeze
    UPGRADING = "UPGRADING".freeze
    SUCCEEDED = "SUCCEEDED".freeze
    FAILED = "FAILED".freeze
    CANCELLED = "CANCELLED".freeze
    SCHEDULED = "SCHEDULED".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [PENDING, DOWNLOADING, QUEUED, PREUPGRADE, UPGRADING, SUCCEEDED, FAILED, CANCELLED, SCHEDULED, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigUpgradeStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigUpgradeStatus"
    end
  end
end
