=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Physical GPU configuration details.
  class ClustermgmtV40ConfigPhysicalGpuConfig < ApiModelBase
    attr_accessor :type

    # Device Id.
    attr_accessor :device_id

    # Device name.
    attr_accessor :device_name

    # Vendor name.
    attr_accessor :vendor_name

    # GPU in use.
    attr_accessor :is_in_use

    # SBDF address.
    attr_accessor :sbdf

    # NUMA node.
    attr_accessor :numa_node

    # GPU assignable.
    attr_accessor :assignable

    attr_accessor :mode

    # Frame buffer size in bytes.
    attr_accessor :frame_buffer_size_bytes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'device_id' => :'deviceId',
        :'device_name' => :'deviceName',
        :'vendor_name' => :'vendorName',
        :'is_in_use' => :'isInUse',
        :'sbdf' => :'sbdf',
        :'numa_node' => :'numaNode',
        :'assignable' => :'assignable',
        :'mode' => :'mode',
        :'frame_buffer_size_bytes' => :'frameBufferSizeBytes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'ClustermgmtV40ConfigGpuType',
        :'device_id' => :'Integer',
        :'device_name' => :'String',
        :'vendor_name' => :'String',
        :'is_in_use' => :'Boolean',
        :'sbdf' => :'String',
        :'numa_node' => :'String',
        :'assignable' => :'Integer',
        :'mode' => :'ClustermgmtV40ConfigGpuMode',
        :'frame_buffer_size_bytes' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigPhysicalGpuConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigPhysicalGpuConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'device_id')
        self.device_id = attributes[:'device_id']
      end

      if attributes.key?(:'device_name')
        self.device_name = attributes[:'device_name']
      end

      if attributes.key?(:'vendor_name')
        self.vendor_name = attributes[:'vendor_name']
      end

      if attributes.key?(:'is_in_use')
        self.is_in_use = attributes[:'is_in_use']
      end

      if attributes.key?(:'sbdf')
        self.sbdf = attributes[:'sbdf']
      end

      if attributes.key?(:'numa_node')
        self.numa_node = attributes[:'numa_node']
      end

      if attributes.key?(:'assignable')
        self.assignable = attributes[:'assignable']
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end

      if attributes.key?(:'frame_buffer_size_bytes')
        self.frame_buffer_size_bytes = attributes[:'frame_buffer_size_bytes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@vendor_name.nil? && @vendor_name.to_s.length > 128
        invalid_properties.push('invalid value for "vendor_name", the character length must be smaller than or equal to 128.')
      end

      if !@vendor_name.nil? && @vendor_name.to_s.length < 0
        invalid_properties.push('invalid value for "vendor_name", the character length must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@vendor_name.nil? && @vendor_name.to_s.length > 128
      return false if !@vendor_name.nil? && @vendor_name.to_s.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] vendor_name Value to be assigned
    def vendor_name=(vendor_name)
      if vendor_name.nil?
        fail ArgumentError, 'vendor_name cannot be nil'
      end

      if vendor_name.to_s.length > 128
        fail ArgumentError, 'invalid value for "vendor_name", the character length must be smaller than or equal to 128.'
      end

      if vendor_name.to_s.length < 0
        fail ArgumentError, 'invalid value for "vendor_name", the character length must be greater than or equal to 0.'
      end

      @vendor_name = vendor_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          device_id == o.device_id &&
          device_name == o.device_name &&
          vendor_name == o.vendor_name &&
          is_in_use == o.is_in_use &&
          sbdf == o.sbdf &&
          numa_node == o.numa_node &&
          assignable == o.assignable &&
          mode == o.mode &&
          frame_buffer_size_bytes == o.frame_buffer_size_bytes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, device_id, device_name, vendor_name, is_in_use, sbdf, numa_node, assignable, mode, frame_buffer_size_bytes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
