=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  class ClustermgmtV40ConfigStorageTier
    SSD_PCIE = "SSD_PCIE".freeze
    SSD_SATA = "SSD_SATA".freeze
    DAS_SATA = "DAS_SATA".freeze
    CLOUD = "CLOUD".freeze
    SSD_MEM_NVME = "SSD_MEM_NVME".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [SSD_PCIE, SSD_SATA, DAS_SATA, CLOUD, SSD_MEM_NVME, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ClustermgmtV40ConfigStorageTier.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ClustermgmtV40ConfigStorageTier"
    end
  end
end
