=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Upload information for a node.
  class ClustermgmtV40ConfigUploadInfoNodeItem < ApiModelBase
    # Provides information on whether hypervisor ISO upload is required or not. This API is not supported for XEN hypervisor type.
    attr_accessor :is_hypervisor_upload_required

    # Indicates if imaging is required or not.
    attr_accessor :is_imaging_mandatory

    # UUID of the host.
    attr_accessor :node_uuid

    # Error message if any, for available hypervisor ISO.
    attr_accessor :available_hypervisor_iso_error

    attr_accessor :required_hypervisor_type

    # Indicates if node is compatible or not.
    attr_accessor :is_node_compatible

    # Md5sum of ISO.
    attr_accessor :md5_sum

    # Name of the hypervisor bundle.
    attr_accessor :bundle_name

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'is_hypervisor_upload_required' => :'isHypervisorUploadRequired',
        :'is_imaging_mandatory' => :'isImagingMandatory',
        :'node_uuid' => :'nodeUuid',
        :'available_hypervisor_iso_error' => :'availableHypervisorIsoError',
        :'required_hypervisor_type' => :'requiredHypervisorType',
        :'is_node_compatible' => :'isNodeCompatible',
        :'md5_sum' => :'md5Sum',
        :'bundle_name' => :'bundleName'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'is_hypervisor_upload_required' => :'Boolean',
        :'is_imaging_mandatory' => :'Boolean',
        :'node_uuid' => :'String',
        :'available_hypervisor_iso_error' => :'String',
        :'required_hypervisor_type' => :'ClustermgmtV40ConfigHypervisorType',
        :'is_node_compatible' => :'Boolean',
        :'md5_sum' => :'String',
        :'bundle_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigUploadInfoNodeItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigUploadInfoNodeItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'is_hypervisor_upload_required')
        self.is_hypervisor_upload_required = attributes[:'is_hypervisor_upload_required']
      end

      if attributes.key?(:'is_imaging_mandatory')
        self.is_imaging_mandatory = attributes[:'is_imaging_mandatory']
      end

      if attributes.key?(:'node_uuid')
        self.node_uuid = attributes[:'node_uuid']
      end

      if attributes.key?(:'available_hypervisor_iso_error')
        self.available_hypervisor_iso_error = attributes[:'available_hypervisor_iso_error']
      end

      if attributes.key?(:'required_hypervisor_type')
        self.required_hypervisor_type = attributes[:'required_hypervisor_type']
      end

      if attributes.key?(:'is_node_compatible')
        self.is_node_compatible = attributes[:'is_node_compatible']
      end

      if attributes.key?(:'md5_sum')
        self.md5_sum = attributes[:'md5_sum']
      end

      if attributes.key?(:'bundle_name')
        self.bundle_name = attributes[:'bundle_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@node_uuid.nil? && @node_uuid !~ pattern
        invalid_properties.push("invalid value for \"node_uuid\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{32}$/)
      if !@md5_sum.nil? && @md5_sum !~ pattern
        invalid_properties.push("invalid value for \"md5_sum\", must conform to the pattern #{pattern}.")
      end

      if !@bundle_name.nil? && @bundle_name.to_s.length > 64
        invalid_properties.push('invalid value for "bundle_name", the character length must be smaller than or equal to 64.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@node_uuid.nil? && @node_uuid !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@md5_sum.nil? && @md5_sum !~ Regexp.new(/^[a-fA-F0-9]{32}$/)
      return false if !@bundle_name.nil? && @bundle_name.to_s.length > 64
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] node_uuid Value to be assigned
    def node_uuid=(node_uuid)
      if node_uuid.nil?
        fail ArgumentError, 'node_uuid cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if node_uuid !~ pattern
        fail ArgumentError, "invalid value for \"node_uuid\", must conform to the pattern #{pattern}."
      end

      @node_uuid = node_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] md5_sum Value to be assigned
    def md5_sum=(md5_sum)
      if md5_sum.nil?
        fail ArgumentError, 'md5_sum cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{32}$/)
      if md5_sum !~ pattern
        fail ArgumentError, "invalid value for \"md5_sum\", must conform to the pattern #{pattern}."
      end

      @md5_sum = md5_sum
    end

    # Custom attribute writer method with validation
    # @param [Object] bundle_name Value to be assigned
    def bundle_name=(bundle_name)
      if bundle_name.nil?
        fail ArgumentError, 'bundle_name cannot be nil'
      end

      if bundle_name.to_s.length > 64
        fail ArgumentError, 'invalid value for "bundle_name", the character length must be smaller than or equal to 64.'
      end

      @bundle_name = bundle_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          is_hypervisor_upload_required == o.is_hypervisor_upload_required &&
          is_imaging_mandatory == o.is_imaging_mandatory &&
          node_uuid == o.node_uuid &&
          available_hypervisor_iso_error == o.available_hypervisor_iso_error &&
          required_hypervisor_type == o.required_hypervisor_type &&
          is_node_compatible == o.is_node_compatible &&
          md5_sum == o.md5_sum &&
          bundle_name == o.bundle_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [is_hypervisor_upload_required, is_imaging_mandatory, node_uuid, available_hypervisor_iso_error, required_hypervisor_type, is_node_compatible, md5_sum, bundle_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
