=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Individual node item details for checking whether hypervisor ISO upload is required or not.
  class ClustermgmtV40ConfigHypervisorUploadNodeListItem < ApiModelBase
    # UUID of the host.
    attr_accessor :node_uuid

    # Host version of the node.
    attr_accessor :hypervisor_version

    # NOS software version of a node.
    attr_accessor :nos_version

    # Rackable unit model type.
    attr_accessor :model

    # Rackable unit Id in which node resides.
    attr_accessor :block_id

    # Indicates whether the node is light compute or not.
    attr_accessor :is_light_compute

    attr_accessor :hypervisor_type

    # Indicates whether the hypervisor is robo mixed or not.
    attr_accessor :is_robo_mixed_hypervisor

    # Indicates if node is minimum compute or not.
    attr_accessor :is_minimum_compute_node

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'node_uuid' => :'nodeUuid',
        :'hypervisor_version' => :'hypervisorVersion',
        :'nos_version' => :'nosVersion',
        :'model' => :'model',
        :'block_id' => :'blockId',
        :'is_light_compute' => :'isLightCompute',
        :'hypervisor_type' => :'hypervisorType',
        :'is_robo_mixed_hypervisor' => :'isRoboMixedHypervisor',
        :'is_minimum_compute_node' => :'isMinimumComputeNode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'node_uuid' => :'String',
        :'hypervisor_version' => :'String',
        :'nos_version' => :'String',
        :'model' => :'String',
        :'block_id' => :'String',
        :'is_light_compute' => :'Boolean',
        :'hypervisor_type' => :'ClustermgmtV40ConfigHypervisorType',
        :'is_robo_mixed_hypervisor' => :'Boolean',
        :'is_minimum_compute_node' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigHypervisorUploadNodeListItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigHypervisorUploadNodeListItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'node_uuid')
        self.node_uuid = attributes[:'node_uuid']
      end

      if attributes.key?(:'hypervisor_version')
        self.hypervisor_version = attributes[:'hypervisor_version']
      end

      if attributes.key?(:'nos_version')
        self.nos_version = attributes[:'nos_version']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'block_id')
        self.block_id = attributes[:'block_id']
      end

      if attributes.key?(:'is_light_compute')
        self.is_light_compute = attributes[:'is_light_compute']
      end

      if attributes.key?(:'hypervisor_type')
        self.hypervisor_type = attributes[:'hypervisor_type']
      end

      if attributes.key?(:'is_robo_mixed_hypervisor')
        self.is_robo_mixed_hypervisor = attributes[:'is_robo_mixed_hypervisor']
      end

      if attributes.key?(:'is_minimum_compute_node')
        self.is_minimum_compute_node = attributes[:'is_minimum_compute_node']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@node_uuid.nil? && @node_uuid !~ pattern
        invalid_properties.push("invalid value for \"node_uuid\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@node_uuid.nil? && @node_uuid !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] node_uuid Value to be assigned
    def node_uuid=(node_uuid)
      if node_uuid.nil?
        fail ArgumentError, 'node_uuid cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if node_uuid !~ pattern
        fail ArgumentError, "invalid value for \"node_uuid\", must conform to the pattern #{pattern}."
      end

      @node_uuid = node_uuid
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          node_uuid == o.node_uuid &&
          hypervisor_version == o.hypervisor_version &&
          nos_version == o.nos_version &&
          model == o.model &&
          block_id == o.block_id &&
          is_light_compute == o.is_light_compute &&
          hypervisor_type == o.hypervisor_type &&
          is_robo_mixed_hypervisor == o.is_robo_mixed_hypervisor &&
          is_minimum_compute_node == o.is_minimum_compute_node
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [node_uuid, hypervisor_version, nos_version, model, block_id, is_light_compute, hypervisor_type, is_robo_mixed_hypervisor, is_minimum_compute_node].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
