=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module NutanixClustermgmt
  # Unconfigured node details.
  class ClustermgmtV40ConfigUnconfiguredNodeListItem
    # Foundation version.
    attr_accessor :foundation_version

    # Rackable unit serial name.
    attr_accessor :rackable_unit_serial

    # UUID of the host.
    attr_accessor :node_uuid

    # Maximum number of nodes in rackable-unit.
    attr_accessor :rackable_unit_max_nodes

    # Current network interface of a node.
    attr_accessor :current_network_interface

    # Position of a node in a rackable unit.
    attr_accessor :node_position

    attr_accessor :cvm_ip

    # Current CVM VLAN tag.
    attr_accessor :current_cvm_vlan_tag

    # Secure boot status.
    attr_accessor :is_secure_booted

    # NOS software version of a node.
    attr_accessor :nos_version

    # CPU type.
    attr_accessor :cpu_type

    attr_accessor :hypervisor_type

    # Host version of the node.
    attr_accessor :hypervisor_version

    # Interface IPV6 address.
    attr_accessor :interface_ipv6

    # Cluster ID.
    attr_accessor :cluster_id

    attr_accessor :attributes

    # Rackable unit model type.
    attr_accessor :rackable_unit_model

    # Cluster arch.
    attr_accessor :arch

    attr_accessor :hypervisor_ip

    attr_accessor :ipmi_ip

    attr_accessor :host_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'foundation_version' => :'foundationVersion',
        :'rackable_unit_serial' => :'rackableUnitSerial',
        :'node_uuid' => :'nodeUuid',
        :'rackable_unit_max_nodes' => :'rackableUnitMaxNodes',
        :'current_network_interface' => :'currentNetworkInterface',
        :'node_position' => :'nodePosition',
        :'cvm_ip' => :'cvmIp',
        :'current_cvm_vlan_tag' => :'currentCvmVlanTag',
        :'is_secure_booted' => :'isSecureBooted',
        :'nos_version' => :'nosVersion',
        :'cpu_type' => :'cpuType',
        :'hypervisor_type' => :'hypervisorType',
        :'hypervisor_version' => :'hypervisorVersion',
        :'interface_ipv6' => :'interfaceIpv6',
        :'cluster_id' => :'clusterId',
        :'attributes' => :'attributes',
        :'rackable_unit_model' => :'rackableUnitModel',
        :'arch' => :'arch',
        :'hypervisor_ip' => :'hypervisorIp',
        :'ipmi_ip' => :'ipmiIp',
        :'host_type' => :'hostType'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'foundation_version' => :'String',
        :'rackable_unit_serial' => :'String',
        :'node_uuid' => :'String',
        :'rackable_unit_max_nodes' => :'Integer',
        :'current_network_interface' => :'String',
        :'node_position' => :'String',
        :'cvm_ip' => :'CommonV10ConfigIPAddress',
        :'current_cvm_vlan_tag' => :'String',
        :'is_secure_booted' => :'Boolean',
        :'nos_version' => :'String',
        :'cpu_type' => :'Array<String>',
        :'hypervisor_type' => :'ClustermgmtV40ConfigHypervisorType',
        :'hypervisor_version' => :'String',
        :'interface_ipv6' => :'String',
        :'cluster_id' => :'String',
        :'attributes' => :'ClustermgmtV40ConfigUnconfiguredNodeAttributeMap',
        :'rackable_unit_model' => :'String',
        :'arch' => :'String',
        :'hypervisor_ip' => :'CommonV10ConfigIPAddress',
        :'ipmi_ip' => :'CommonV10ConfigIPAddress',
        :'host_type' => :'ClustermgmtV40ConfigHostTypeEnum'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixClustermgmt::ClustermgmtV40ConfigUnconfiguredNodeListItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixClustermgmt::ClustermgmtV40ConfigUnconfiguredNodeListItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'foundation_version')
        self.foundation_version = attributes[:'foundation_version']
      end

      if attributes.key?(:'rackable_unit_serial')
        self.rackable_unit_serial = attributes[:'rackable_unit_serial']
      end

      if attributes.key?(:'node_uuid')
        self.node_uuid = attributes[:'node_uuid']
      end

      if attributes.key?(:'rackable_unit_max_nodes')
        self.rackable_unit_max_nodes = attributes[:'rackable_unit_max_nodes']
      end

      if attributes.key?(:'current_network_interface')
        self.current_network_interface = attributes[:'current_network_interface']
      end

      if attributes.key?(:'node_position')
        self.node_position = attributes[:'node_position']
      end

      if attributes.key?(:'cvm_ip')
        self.cvm_ip = attributes[:'cvm_ip']
      end

      if attributes.key?(:'current_cvm_vlan_tag')
        self.current_cvm_vlan_tag = attributes[:'current_cvm_vlan_tag']
      end

      if attributes.key?(:'is_secure_booted')
        self.is_secure_booted = attributes[:'is_secure_booted']
      end

      if attributes.key?(:'nos_version')
        self.nos_version = attributes[:'nos_version']
      end

      if attributes.key?(:'cpu_type')
        if (value = attributes[:'cpu_type']).is_a?(Array)
          self.cpu_type = value
        end
      end

      if attributes.key?(:'hypervisor_type')
        self.hypervisor_type = attributes[:'hypervisor_type']
      end

      if attributes.key?(:'hypervisor_version')
        self.hypervisor_version = attributes[:'hypervisor_version']
      end

      if attributes.key?(:'interface_ipv6')
        self.interface_ipv6 = attributes[:'interface_ipv6']
      end

      if attributes.key?(:'cluster_id')
        self.cluster_id = attributes[:'cluster_id']
      end

      if attributes.key?(:'attributes')
        self.attributes = attributes[:'attributes']
      end

      if attributes.key?(:'rackable_unit_model')
        self.rackable_unit_model = attributes[:'rackable_unit_model']
      end

      if attributes.key?(:'arch')
        self.arch = attributes[:'arch']
      end

      if attributes.key?(:'hypervisor_ip')
        self.hypervisor_ip = attributes[:'hypervisor_ip']
      end

      if attributes.key?(:'ipmi_ip')
        self.ipmi_ip = attributes[:'ipmi_ip']
      end

      if attributes.key?(:'host_type')
        self.host_type = attributes[:'host_type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@node_uuid.nil? && @node_uuid !~ pattern
        invalid_properties.push("invalid value for \"node_uuid\", must conform to the pattern #{pattern}.")
      end

      if !@cpu_type.nil? && @cpu_type.length > 1024
        invalid_properties.push('invalid value for "cpu_type", number of items must be less than or equal to 1024.')
      end

      if !@cpu_type.nil? && @cpu_type.length < 0
        invalid_properties.push('invalid value for "cpu_type", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@node_uuid.nil? && @node_uuid !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@cpu_type.nil? && @cpu_type.length > 1024
      return false if !@cpu_type.nil? && @cpu_type.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] node_uuid Value to be assigned
    def node_uuid=(node_uuid)
      if node_uuid.nil?
        fail ArgumentError, 'node_uuid cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if node_uuid !~ pattern
        fail ArgumentError, "invalid value for \"node_uuid\", must conform to the pattern #{pattern}."
      end

      @node_uuid = node_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] cpu_type Value to be assigned
    def cpu_type=(cpu_type)
      if cpu_type.nil?
        fail ArgumentError, 'cpu_type cannot be nil'
      end

      if cpu_type.length > 1024
        fail ArgumentError, 'invalid value for "cpu_type", number of items must be less than or equal to 1024.'
      end

      if cpu_type.length < 0
        fail ArgumentError, 'invalid value for "cpu_type", number of items must be greater than or equal to 0.'
      end

      @cpu_type = cpu_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          foundation_version == o.foundation_version &&
          rackable_unit_serial == o.rackable_unit_serial &&
          node_uuid == o.node_uuid &&
          rackable_unit_max_nodes == o.rackable_unit_max_nodes &&
          current_network_interface == o.current_network_interface &&
          node_position == o.node_position &&
          cvm_ip == o.cvm_ip &&
          current_cvm_vlan_tag == o.current_cvm_vlan_tag &&
          is_secure_booted == o.is_secure_booted &&
          nos_version == o.nos_version &&
          cpu_type == o.cpu_type &&
          hypervisor_type == o.hypervisor_type &&
          hypervisor_version == o.hypervisor_version &&
          interface_ipv6 == o.interface_ipv6 &&
          cluster_id == o.cluster_id &&
          attributes == o.attributes &&
          rackable_unit_model == o.rackable_unit_model &&
          arch == o.arch &&
          hypervisor_ip == o.hypervisor_ip &&
          ipmi_ip == o.ipmi_ip &&
          host_type == o.host_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [foundation_version, rackable_unit_serial, node_uuid, rackable_unit_max_nodes, current_network_interface, node_position, cvm_ip, current_cvm_vlan_tag, is_secure_booted, nos_version, cpu_type, hypervisor_type, hypervisor_version, interface_ipv6, cluster_id, attributes, rackable_unit_model, arch, hypervisor_ip, ipmi_ip, host_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NutanixClustermgmt.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
