=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixClustermgmt::ClustermgmtV40ConfigHypervisorReference
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixClustermgmt::ClustermgmtV40ConfigHypervisorReference do
  #let(:instance) { NutanixClustermgmt::ClustermgmtV40ConfigHypervisorReference.new }

  describe 'test an instance of ClustermgmtV40ConfigHypervisorReference' do
    it 'should create an instance of ClustermgmtV40ConfigHypervisorReference' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixClustermgmt::ClustermgmtV40ConfigHypervisorReference)
    end
  end

  describe 'test attribute "external_address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "full_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "number_of_vms"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "acropolis_connection_state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
