=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixClustermgmt::ClustermgmtV40ConfigExpandClusterParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixClustermgmt::ClustermgmtV40ConfigExpandClusterParams do
  let(:instance) { NutanixClustermgmt::ClustermgmtV40ConfigExpandClusterParams.new }

  describe 'test an instance of ClustermgmtV40ConfigExpandClusterParams' do
    it 'should create an instance of ClustermgmtV40ConfigExpandClusterParams' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixClustermgmt::ClustermgmtV40ConfigExpandClusterParams)
    end
  end

  describe 'test attribute "node_params"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "config_params"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "should_skip_add_node"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "should_skip_pre_expand_checks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
