=begin
#Nutanix Cluster Management APIs

#Manage Hosts, Clusters and other Infrastructure.

The version of the OpenAPI document: 4.0.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixClustermgmt::ClustermgmtV40ConfigPartitionType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixClustermgmt::ClustermgmtV40ConfigPartitionType do
  let(:instance) { NutanixClustermgmt::ClustermgmtV40ConfigPartitionType.new }

  describe 'test an instance of ClustermgmtV40ConfigPartitionType' do
    it 'should create an instance of ClustermgmtV40ConfigPartitionType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixClustermgmt::ClustermgmtV40ConfigPartitionType)
    end
  end

end
